# sharpe, calmar, sortino, omega, serenity, smart sharpe, smart sortino, net profit
fitness-ratio: 'net profit'
optimal-total: 300

optimizer: 'RandomRestartHillClimbingOptimizer'
n_iter: 1000

optimizer_step2: 'PowellsMethod'
n_iter_step2: 1000

optimizer_rolling: 'PowellsMethod'
n_iter_rolling: 100

# -1 all cpu
n_jobs: 10

n_best_candidates: 5

RandomSearchOptimizer:

EvolutionStrategyOptimizer:
  population: 25
  mutation_rate: 0.0333
  crossover_rate: 0.6
  rand_rest_p: 0.05 # swapping_prob
  
RandomRestartHillClimbingOptimizer:
  epsilon: 0.1
  distribution: "laplace"
  n_neighbours: 4
  rand_rest_p: 0.1
  n_iter_restart: 20

HillClimbingOptimizer:
  epsilon: 0.1
  distribution: "laplace"
  n_neighbours: 4
  rand_rest_p: 0.1  

PowellsMethod:
  iters_p_dim: 10

ParticleSwarmOptimizer:
  inertia: 0.4
  cognitive_weight: 0.7
  social_weight: 0.7
  temp_weight: 0.3
  rand_rest_p: 0.05

TreeStructuredParzenEstimators:
  gamma_tpe: 0.5
  rand_rest_p: 0.7

strategy_name: 'Test'

starting_balance: 2000
fee: 0.00075
futures_leverage: 1
futures_leverage_mode: cross
settlement_currency: USDT
warm_up_candles: 1000
exchange: Binance
symbol: 'HBAR-USDT'
timeframe: '15m'

timespan:
  start_date: '2021-04-01'
  finish_date: '2022-03-31'


extra_routes:
#  0:
#    exchange: 'Binance'
#    symbol: 'BTC-USDT'
#    timeframe: '15m'

